USE School
GO

CREATE PROCEDURE dbo.DeleteStudentRecord
(
    @Id BIGINT
)
As
SET NOCOUNT ON
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
    BEGIN TRANSACTION
        UPDATE Students
            SET Deleted = 1
        WHERE Id = @Id
    COMMIT TRANSACTION
END
