USE School
GO

CREATE PROCEDURE dbo.RemoveStudentRecord
(
    @Id BIGINT
)
As
SET NOCOUNT ON
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
    BEGIN TRANSACTION
        DELETE from Students where Id=@Id
    COMMIT TRANSACTION
END
