USE School
GO

Create PROCEDURE dbo.SelectStudentById
(
  @Id BIGINT
)
AS

SET NOCOUNT ON
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
  BEGIN TRANSACTION
        SELECT TOP 1 Id,FirstName,LastName,Gpa FROM Students 
        WHERE @Id = Id AND DELETED = 0
    COMMIT TRANSACTION
END