USE School
GO

Create PROCEDURE dbo.SelectAllStudents
AS

SET NOCOUNT ON
BEGIN
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
  BEGIN TRANSACTION
        SELECT Id,FirstName,LastName,Gpa FROM Students 
        WHERE DELETED = 0
    COMMIT TRANSACTION
END
