---
- name: install prerequisite packages
  apt:
    name: 
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Add Docker repository key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: add docker repository
  apt_repository: 
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
    update_cache: yes
    state: present

- name: Install (or update) docker 
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
    cache_valid_time: 86400

- name: confirm docker functions
  shell: docker run hello-world

